CREATE DATABASE LibraryDB
GO

USE LibraryDB
GO

CREATE TABLE Books(
BookID INT PRIMARY KEY IDENTITY(1,1),
Title NVARCHAR(255) NOT NULL,
Author NVARCHAR(255) NOT NULL,
PublishedYear INT
)
GO

CREATE TABLE Members(
MemberID INT PRIMARY KEY IDENTITY(1,1),
FullName NVARCHAR(255),
JoinDate DATE NOT NULL,
Email NVARCHAR(255),
)
GO

CREATE TABLE Loans(
LoanID INT PRIMARY KEY IDENTITY(1,1),
LoanDate DATE NOT NULL,
BookID INT NOT NULL,
MemberID INT NOT NULL
FOREIGN KEY(BookID) REFERENCES Books(BookID),
FOREIGN KEY (MemberID) REFERENCES Members(MemberID)
)
GO